//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class DCOMPROMISO
    {
        public decimal VIGENCIA { get; set; }
        public decimal NUM_COMPROMISO { get; set; }
        public string COD_UNIDAD { get; set; }
        public string COD_GASTO { get; set; }
        public string COD_RECURSO { get; set; }
        public Nullable<decimal> VAL_COMPROMISO { get; set; }
        public Nullable<decimal> VAL_OBLIGACION { get; set; }
        public Nullable<decimal> VAL_TRAMITE { get; set; }
        public Nullable<decimal> VAL_PAGOS { get; set; }
        public Nullable<decimal> VAL_ANTICIPO { get; set; }
        public string TIP_PAC { get; set; }
        public decimal COD_PAC { get; set; }
    
        public virtual MCOMPROMISO MCOMPROMISO { get; set; }
    }
    
}
