//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class DEGRESO
    {
        public decimal NUM_EGRESO { get; set; }
        public string CLS_EGRESO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string NIT { get; set; }
        public string BEN_CHEQUE { get; set; }
        public string NRO_CTABANCARIA { get; set; }
        public string COD_BANCO { get; set; }
        public Nullable<decimal> NRO_CHEQUE { get; set; }
        public decimal VAL_TOTAL { get; set; }
        public decimal VAL_NETO { get; set; }
        public Nullable<System.DateTime> FEC_PAGO { get; set; }
        public string MONTO_ESCRITO { get; set; }
        public string COD_UNIDAD { get; set; }
        public Nullable<decimal> SEC_OPERACION { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_ENTREGA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public string CTA_BANCO { get; set; }
        public string COD_BANCO_NIT { get; set; }
        public string TIPO_CTA_BANCO { get; set; }
    }
    
}
