//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class DRESERVA
    {
        public decimal VIGENCIA { get; set; }
        public decimal NUM_CERTIFICADO { get; set; }
        public string COD_UNIDAD { get; set; }
        public string COD_GASTO { get; set; }
        public string COD_RECURSO { get; set; }
        public Nullable<decimal> VAL_CERTIFICADO { get; set; }
        public Nullable<decimal> VAL_COMPROMISO { get; set; }
        public Nullable<decimal> VAL_OBLIGACION { get; set; }
        public Nullable<decimal> VAL_PAGOS { get; set; }
        public Nullable<decimal> TRAMITE_CONTRATO { get; set; }
    
        public virtual MRESERVA MRESERVA { get; set; }
    }
    
}
