//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class MEGRESO
    {
        public decimal NUM_EGRESO { get; set; }
        public string CLS_EGRESO { get; set; }
        public System.DateTime FEC_EGRESO { get; set; }
        public string CON_EGRESO { get; set; }
        public Nullable<decimal> COD_ORDEN { get; set; }
        public string ORIGEN { get; set; }
        public decimal VAL_EGRESO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> SEC_OPERACION { get; set; }
        public string CLASIFICACION { get; set; }
        public string COD_UNIDAD { get; set; }
        public string MB_MO { get; set; }
        public string MONTO_ESCRITO { get; set; }
        public string CHK_PARTIALPAY { get; set; }
        public decimal VALOR_CAMBIO { get; set; }
        public string COD_MONEDA { get; set; }
        public string DEVOLUCION { get; set; }
    }
    
}
