//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class MORDEN_EGRESO
    {
        public decimal VIGENCIA { get; set; }
        public decimal NUM_ORDEN { get; set; }
        public Nullable<decimal> NUM_EGRESO { get; set; }
        public string CLS_EGRESO { get; set; }
        public Nullable<System.DateTime> FEC_EGRESO { get; set; }
        public Nullable<decimal> VAL_PAGADO { get; set; }
    }
    
}
