//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class MRESERVA
    {
        public MRESERVA()
        {
            this.DRESERVA = new HashSet<DRESERVA>();
            this.MCOMPROMISO = new HashSet<MCOMPROMISO>();
        }
    
        public decimal VIGENCIA { get; set; }
        public decimal NUM_CERTIFICADO { get; set; }
        public System.DateTime FEC_EXPEDICION { get; set; }
        public System.DateTime FEC_VENCIMIENTO { get; set; }
        public decimal NRO_PRORROGA { get; set; }
        public string OBJ_CERTIFICADO { get; set; }
        public string DEP_SOLICITANTE { get; set; }
        public decimal ESTADO { get; set; }
        public Nullable<System.DateTime> FEC_ANULADO { get; set; }
        public string VIG_FUTURA { get; set; }
        public Nullable<decimal> TRAMITE_CONTRATO { get; set; }
        public string CONTRIBUCION { get; set; }
        public Nullable<decimal> CDP_CONTRIBUCION { get; set; }
        public Nullable<decimal> NUM_CERTIFICADO_VA { get; set; }
        public string INT_PREVIO { get; set; }
        public string CDP_MACRO_PREVIO { get; set; }
        public decimal VALOR_CAMBIO { get; set; }
    
        public virtual ICollection<DRESERVA> DRESERVA { get; set; }
        public virtual ICollection<MCOMPROMISO> MCOMPROMISO { get; set; }
    }
    
}
