//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class PPTO_GASTOS_V1
    {
        public decimal VIGENCIA { get; set; }
        public string COD_UNIDAD { get; set; }
        public string COD_GASTO { get; set; }
        public string COD_RECURSO { get; set; }
        public string NOM_GASTO { get; set; }
        public decimal APROP_INICIAL { get; set; }
        public Nullable<decimal> APROP_ADICIONAL { get; set; }
        public Nullable<decimal> APROP_REDUCIDA { get; set; }
        public Nullable<decimal> APROP_DEFINITIVA { get; set; }
        public Nullable<decimal> CONGELACIONES { get; set; }
        public Nullable<decimal> CERTIFICACIONES { get; set; }
        public Nullable<decimal> APROP_DISPONIBLE { get; set; }
        public Nullable<decimal> COMPROMISOS { get; set; }
        public Nullable<decimal> OBLIGACIONES { get; set; }
        public Nullable<decimal> PAGOS { get; set; }
        public Nullable<decimal> APROP_POR_COMPROMETER { get; set; }
        public Nullable<decimal> SAL_CERTIFICADOS { get; set; }
        public Nullable<decimal> SAL_COMPROMISOS { get; set; }
        public Nullable<decimal> CUENTAS_POR_PAGAR { get; set; }
        public Nullable<decimal> RES_CAJA { get; set; }
        public Nullable<decimal> RES_APROPIACION { get; set; }
        public Nullable<decimal> APROP_TRAMITE { get; set; }
        public Nullable<decimal> REINTEGROS { get; set; }
        public string TIP_PAC { get; set; }
        public decimal COD_PAC { get; set; }
        public string CON_SITUACION { get; set; }
        public string DIS_INTERNA { get; set; }
        public Nullable<decimal> NIVEL_INTERNO { get; set; }
        public string RUBRO { get; set; }
        public string RUBRO_AUX { get; set; }
        public string GASTO { get; set; }
        public string GASTO_AUX { get; set; }
        public string CLASE { get; set; }
        public string CUENTA { get; set; }
        public string SUBCUENTA { get; set; }
        public string OBJETO { get; set; }
        public string ORDINAL { get; set; }
        public string SUBORDINAL { get; set; }
        public string NIVEL_AUX1 { get; set; }
        public string NIVEL_AUX2 { get; set; }
        public string NIVEL_AUX3 { get; set; }
        public string NIVEL_AUX4 { get; set; }
        public string NIVEL_AUX5 { get; set; }
        public string NIVEL_AUX6 { get; set; }
        public string CTRL_RESERVA { get; set; }
        public string NIVEL { get; set; }
    }
    
}
