//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class AN_PCONTRATO
    {
        public string PRO_SEL_NRO { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual PCONTRATOS PCONTRATOS { get; set; }
    }
    
}
