//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class ANX_CONTRATOS
    {
        public string TIP_DOC { get; set; }
        public string NOM_DOC { get; set; }
        public string OBS_DOC { get; set; }
        public string COD_CON { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FEC_REG { get; set; }
    
        public virtual TIP_DOC TIP_DOC1 { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
    
}
