//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class AUDITORIA
    {
        public int ID_AUD { get; set; }
        public string OBJ_AUD { get; set; }
        public string ACC_AUD { get; set; }
        public System.DateTime FEC_AUD { get; set; }
        public string USU_AUD { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
    
}
