//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CFORMA_PAGO
    {
        public decimal ID { get; set; }
        public string COD_CON { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public string TIPO_PAGO { get; set; }
        public Nullable<decimal> VALOR_PAGO { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string PAGA_GOBER { get; set; }
    
        public virtual TIPO_PAGO TIPO_PAGO1 { get; set; }
    }
    
}
