//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CMINUTAS
    {
        public string CMIN_CODI { get; set; }
        public string CMIN_NOMB { get; set; }
        public string CMIN_ENCA { get; set; }
        public string CMIN_BODY { get; set; }
        public string CMIN_PIEP { get; set; }
        public string CMIN_CAMP { get; set; }
        public string CMIN_VISTA { get; set; }
        public string CMIN_USBD { get; set; }
        public string CMIN_USAP { get; set; }
        public string CMIN_ESTA { get; set; }
        public Nullable<System.DateTime> CMIN_FREG { get; set; }
        public Nullable<System.DateTime> CMIN_FNOV { get; set; }
    }
    
}
