//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CON_POLIZAS
    {
        public decimal COD_POL { get; set; }
        public string COD_CON { get; set; }
        public Nullable<decimal> POR_SMMLV { get; set; }
        public string CAL_APARTIRDE { get; set; }
        public Nullable<decimal> VIGENCIA { get; set; }
        public string APARTIRDE { get; set; }
        public string TIPO { get; set; }
    }
    
}
