//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CORREOSE
    {
        public string CORR_CODI { get; set; }
        public string CORR_NOMB { get; set; }
        public string CORR_DATO { get; set; }
        public string CORR_BODY { get; set; }
        public string CORR_ESTA { get; set; }
        public string CORR_USAP { get; set; }
        public string CORR_USBD { get; set; }
        public Nullable<System.DateTime> CORR_FREG { get; set; }
        public Nullable<System.DateTime> CORR_FNOV { get; set; }
        public string CORR_CAMP { get; set; }
        public string CORR_VISTA { get; set; }
    }
    
}
