//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CTRL_ENTIDAD
    {
        public string COD_SECPRINCIPAL { get; set; }
        public string NOM_SECPRINCIPAL { get; set; }
        public string NIT { get; set; }
        public string REPRESENTANTE_LEGAL { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string PAIS { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string CIUDAD { get; set; }
        public string MUNICIPIO { get; set; }
        public byte[] LOGO_RPT { get; set; }
    }
    
}
