//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class DEPENDENCIA
    {
        public DEPENDENCIA()
        {
            this.CONS_PROC = new HashSet<CONS_PROC>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.CONTRATOS1 = new HashSet<CONTRATOS>();
            this.HDEP_ABOGADOS = new HashSet<HDEP_ABOGADOS>();
            this.MOD_CONTRATOS = new HashSet<MOD_CONTRATOS>();
            this.MOD_CONTRATOS1 = new HashSet<MOD_CONTRATOS>();
            this.ESTPREV = new HashSet<ESTPREV>();
            this.ESTPREV1 = new HashSet<ESTPREV>();
            this.ESTPREV2 = new HashSet<ESTPREV>();
            this.PCONTRATOS = new HashSet<PCONTRATOS>();
            this.PCONTRATOS1 = new HashSet<PCONTRATOS>();
            this.PSOLICITUDES = new HashSet<PSOLICITUDES>();
            this.PSOLICITUDES1 = new HashSet<PSOLICITUDES>();
        }
    
        public string COD_DEP { get; set; }
        public string NOM_DEP { get; set; }
        public string DEP_DEL { get; set; }
        public string DEP_ABR { get; set; }
        public string IDE_TER { get; set; }
        public string NORMA_DEL { get; set; }
        public string ESTADO { get; set; }
        public string EMAIL { get; set; }
        public string CARGO_ENC { get; set; }
        public string INT_PRO { get; set; }
    
        public virtual ICollection<CONS_PROC> CONS_PROC { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS1 { get; set; }
        public virtual ICollection<HDEP_ABOGADOS> HDEP_ABOGADOS { get; set; }
        public virtual ICollection<MOD_CONTRATOS> MOD_CONTRATOS { get; set; }
        public virtual ICollection<MOD_CONTRATOS> MOD_CONTRATOS1 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV1 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV2 { get; set; }
        public virtual ICollection<PCONTRATOS> PCONTRATOS { get; set; }
        public virtual ICollection<PCONTRATOS> PCONTRATOS1 { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES1 { get; set; }
    }
    
}
