//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class DOCU_PROC
    {
        public string COD_TPROC { get; set; }
        public string COD_ETAPA { get; set; }
        public string COD_TDOC { get; set; }
        public string DOC_OBLIG { get; set; }
        public string DOC_EST { get; set; }
    }
    
}
