//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_CARGO
    {
        public EP_CARGO()
        {
            this.ESTPREV = new HashSet<ESTPREV>();
            this.ESTPREV1 = new HashSet<ESTPREV>();
            this.ESTPREV2 = new HashSet<ESTPREV>();
            this.ESTPREV3 = new HashSet<ESTPREV>();
        }
    
        public string COD_CARGO { get; set; }
        public string DES_CARGO { get; set; }
        public string VIG_CARGO { get; set; }
        public string EST_CARGO { get; set; }
    
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV1 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV2 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV3 { get; set; }
    }
    
}
