//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_CDP
    {
        public EP_CDP()
        {
            this.EP_RUBROS_CDP = new HashSet<EP_RUBROS_CDP>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> ID_EP { get; set; }
        public string NRO_CDP { get; set; }
        public System.DateTime FEC_CDP { get; set; }
        public Nullable<decimal> VAL_CDP { get; set; }
        public string VIG_FUT { get; set; }
        public Nullable<decimal> GRUPO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP_MOD { get; set; }
    
        public virtual ICollection<EP_RUBROS_CDP> EP_RUBROS_CDP { get; set; }
        public virtual ESTPREV ESTPREV { get; set; }
    }
    
}
