//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_HESTADOEP
    {
        public EP_HESTADOEP()
        {
            this.ESTPREV_1 = new HashSet<ESTPREV>();
            this.ESTPREV1 = new HashSet<ESTPREV>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> ID_EP { get; set; }
        public Nullable<System.DateTime> FEC_EP { get; set; }
        public Nullable<System.DateTime> FSIS_EP { get; set; }
        public string USAP_EP { get; set; }
        public string OBS_EP { get; set; }
        public string TIP_EP { get; set; }
        public string EST_EP { get; set; }
    
        public virtual ESTPREV ESTPREV { get; set; }
        public virtual TERCEROS TERCEROS { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV_1 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV1 { get; set; }
    }
    
}
