//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_POLIZAS
    {
        public decimal ID { get; set; }
        public Nullable<int> COD_POL { get; set; }
        public Nullable<decimal> ID_EP { get; set; }
        public Nullable<decimal> POR_SMMLV { get; set; }
        public string CAL_APARTIRDE { get; set; }
        public Nullable<decimal> VIGENCIA { get; set; }
        public string APARTIRDE { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> GRUPO { get; set; }
    
        public virtual CAL_VIG_POL CAL_VIG_POL { get; set; }
        public virtual CALCULOPOL CALCULOPOL { get; set; }
        public virtual POLIZAS POLIZAS { get; set; }
        public virtual ESTPREV ESTPREV { get; set; }
    }
    
}
