//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_RUBROS_CDP
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_EP { get; set; }
        public string COD_RUB { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string NRO_CDP { get; set; }
        public Nullable<short> VIG_CDP { get; set; }
        public Nullable<int> GRUPO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP_MOD { get; set; }
        public Nullable<decimal> ID_EP_CDP { get; set; }
    
        public virtual RUBROS RUBROS { get; set; }
        public virtual EP_CDP EP_CDP { get; set; }
    }
    
}
