//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class ESTADOS
    {
        public ESTADOS()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.ESTCONTRATOS = new HashSet<ESTCONTRATOS>();
            this.ESTCONTRATOS1 = new HashSet<ESTCONTRATOS>();
            this.MOD_CONTRATOS = new HashSet<MOD_CONTRATOS>();
            this.ESTADOS1 = new HashSet<ESTADOS>();
            this.ESTADOS2 = new HashSet<ESTADOS>();
        }
    
        public string COD_EST { get; set; }
        public string NOM_EST { get; set; }
        public string TIP_EST { get; set; }
        public string SIGLA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<ESTCONTRATOS> ESTCONTRATOS { get; set; }
        public virtual ICollection<ESTCONTRATOS> ESTCONTRATOS1 { get; set; }
        public virtual ICollection<MOD_CONTRATOS> MOD_CONTRATOS { get; set; }
        public virtual ICollection<ESTADOS> ESTADOS1 { get; set; }
        public virtual ICollection<ESTADOS> ESTADOS2 { get; set; }
    }
    
}
