//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GPOBLIGACIONES
    {
        public string NUM_PCON { get; set; }
        public int IDE_OBLIG { get; set; }
        public string DES_OBLIG2 { get; set; }
        public string DES_OBLIG { get; set; }
        public int GRUPO { get; set; }
    
        public virtual GPROCESOS GPROCESOS { get; set; }
    }
    
}
