//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GPPROYECTOS
    {
        public string PROYECTO { get; set; }
        public string NUM_PROC { get; set; }
        public int GRUPO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
        public string USAP { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USBD_MOD { get; set; }
        public string USAP_MOD { get; set; }
    
        public virtual PROYECTOS PROYECTOS { get; set; }
        public virtual GPROCESOS GPROCESOS { get; set; }
    }
    
}
