//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GPROCESOS
    {
        public GPROCESOS()
        {
            this.CDP_GPROCESOS = new HashSet<CDP_GPROCESOS>();
            this.GPOBLIGACIONES = new HashSet<GPOBLIGACIONES>();
            this.GPPOLIZAS = new HashSet<GPPOLIZAS>();
            this.GPPROPONENTES = new HashSet<GPPROPONENTES>();
            this.GPPROYECTOS = new HashSet<GPPROYECTOS>();
            this.RUBROS_GPROCESOS = new HashSet<RUBROS_GPROCESOS>();
            this.PAGOS_GPROCESOS = new HashSet<PAGOS_GPROCESOS>();
            this.MOD_PROPONENTES = new HashSet<MOD_PROPONENTES>();
        }
    
        public string PRO_SEL_NRO { get; set; }
        public string IDE_CON { get; set; }
        public string OBJ_CON { get; set; }
        public string PRO_CON { get; set; }
        public int PLA_EJE_CON { get; set; }
        public string DEP_CON { get; set; }
        public string DEP_PCON { get; set; }
        public short VIG_CON { get; set; }
        public string TIP_CON { get; set; }
        public string STIP_CON { get; set; }
        public decimal VAL_CON { get; set; }
        public decimal VAL_APO_GOB { get; set; }
        public string COD_SEC { get; set; }
        public string TIP_FOR { get; set; }
        public string OTR_CNS { get; set; }
        public string NRO_PLA_CON { get; set; }
        public string IDE_REP { get; set; }
        public string URG_MAN { get; set; }
        public string EST_CONV { get; set; }
        public string APL_GAC { get; set; }
        public string EST_CON { get; set; }
        public string COD_CON { get; set; }
        public Nullable<int> NRO_CON { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string LUG_EJE { get; set; }
        public string USUENCARGADO { get; set; }
        public Nullable<System.DateTime> FECHAASIG { get; set; }
        public Nullable<System.DateTime> FECHARECIBIDO { get; set; }
        public string NUM_SOL { get; set; }
        public string COD_TPRO { get; set; }
        public string ESTADO { get; set; }
        public string TIPO_PLAZO { get; set; }
        public int GRUPO { get; set; }
        public string DESC_GRUPO { get; set; }
        public Nullable<decimal> PLAZO2_EJE_CON { get; set; }
        public string TIPO_PLAZO2 { get; set; }
        public Nullable<decimal> VAL_SIN_IVA { get; set; }
        public string INTERVENTORIA { get; set; }
        public string AGOTAR_PPTO { get; set; }
        public string CONSIDERANDOS { get; set; }
        public string APORTES { get; set; }
        public string REVISADOPOR { get; set; }
        public string OBS_PROYECTOS { get; set; }
        public string OBS_CDP { get; set; }
        public string OBS_POLIZAS { get; set; }
    
        public virtual ICollection<CDP_GPROCESOS> CDP_GPROCESOS { get; set; }
        public virtual ICollection<GPOBLIGACIONES> GPOBLIGACIONES { get; set; }
        public virtual ICollection<GPPOLIZAS> GPPOLIZAS { get; set; }
        public virtual ICollection<GPPROPONENTES> GPPROPONENTES { get; set; }
        public virtual ICollection<GPPROYECTOS> GPPROYECTOS { get; set; }
        public virtual PCONTRATOS PCONTRATOS { get; set; }
        public virtual ICollection<RUBROS_GPROCESOS> RUBROS_GPROCESOS { get; set; }
        public virtual ICollection<PAGOS_GPROCESOS> PAGOS_GPROCESOS { get; set; }
        public virtual ICollection<MOD_PROPONENTES> MOD_PROPONENTES { get; set; }
        public virtual TIPOSPROC TIPOSPROC { get; set; }
        public virtual PESTADOS PESTADOS { get; set; }
    }
    
}
