//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class HAUDITORIA
    {
        public decimal HAUDCODI { get; set; }
        public string HAUDTABL { get; set; }
        public string HAUDIDEN { get; set; }
        public string HAUDTIPO { get; set; }
        public string HAUDDESC { get; set; }
        public string HAUDUSER { get; set; }
        public System.DateTime HAUDFESI { get; set; }
        public string HAUDUSBD { get; set; }
    }
    
}
