//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class HORAS
    {
        public decimal COD_HOR { get; set; }
        public string NOM_HOR { get; set; }
        public string JOR_HOR { get; set; }
        public string NOM_HMIL { get; set; }
        public string LABORALES { get; set; }
    }
    
}
