//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class HREVISADO
    {
        public HREVISADO()
        {
            this.PSOLICITUDES1 = new HashSet<PSOLICITUDES>();
        }
    
        public string COD_SOL { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBIDO { get; set; }
        public Nullable<System.DateTime> FEC_REC_ABOG { get; set; }
        public string RECIBIDO_ABOG { get; set; }
        public string OBS_RECIBIDO_ABOG { get; set; }
        public Nullable<System.DateTime> FECHA_REVISADO { get; set; }
        public string OBS_REVISADO { get; set; }
        public string CONCEPTO_REVISADO { get; set; }
        public Nullable<decimal> ID_HREV { get; set; }
        public string NIT_ABOG_RECIBE { get; set; }
        public string OBSERVACION_RECIBIDO { get; set; }
        public Nullable<System.DateTime> FEC_ASIGNADO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP { get; set; }
        public string HOBS_REVISADO { get; set; }
        public decimal IDE { get; set; }
    
        public virtual TERCEROS TERCEROS { get; set; }
        public virtual PSOLICITUDES PSOLICITUDES { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES1 { get; set; }
    }
    
}
