//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class IMPUESTOS
    {
        public int NRO_IMP { get; set; }
        public string NOM_IMP { get; set; }
        public Nullable<int> COD_PCT { get; set; }
        public string ESTADO { get; set; }
    }
    
}
