//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_GP_SEG_DOC
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_DOC { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string EST_INI { get; set; }
        public string EST_FIN { get; set; }
        public string OBS_SEG { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
    }
    
}
