//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_GP_USU_ROL
    {
        public string VIG_RUT { get; set; }
        public string USUARIO { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAPM { get; set; }
        public string USBDM { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string EST_ROL { get; set; }
        public decimal ID_ROL { get; set; }
        public Nullable<decimal> ID_RUT { get; set; }
    
        public virtual TERCEROS TERCEROS { get; set; }
    }
    
}
