//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_INCO_SOP
    {
        public string COD_CON { get; set; }
        public decimal NUM_INF { get; set; }
        public byte[] SOPORTE { get; set; }
        public string CONTENT { get; set; }
        public string ICONO { get; set; }
        public string NOMARC { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP_M { get; set; }
        public string USBD_M { get; set; }
        public string SOP_EST { get; set; }
        public int ID { get; set; }
    
        public virtual INT_INFOCONT INT_INFOCONT { get; set; }
    }
    
}
