//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_GP_RP_OP
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_DOC { get; set; }
        public Nullable<decimal> NRO_RP { get; set; }
        public Nullable<decimal> VIG_RP { get; set; }
        public Nullable<decimal> NRO_ORD { get; set; }
        public Nullable<System.DateTime> FEC_ORD { get; set; }
        public Nullable<decimal> NRO_EGR { get; set; }
        public Nullable<System.DateTime> FEC_EGR { get; set; }
        public string EST_ORD { get; set; }
    }
    
}
