//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_GP_RUT_EST
    {
        public short VIG_RUT { get; set; }
        public string EST_DE { get; set; }
        public string EST_PARA { get; set; }
        public string CLA_RUT { get; set; }
        public string USBD { get; set; }
        public string USAP { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBDM { get; set; }
        public string USAPM { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string EST_RUT { get; set; }
        public decimal ID_RUT { get; set; }
        public Nullable<decimal> ID { get; set; }
    
        public virtual INT_GP_CLA_EST INT_GP_CLA_EST { get; set; }
        public virtual INT_GP_EST INT_GP_EST { get; set; }
        public virtual INT_GP_EST INT_GP_EST1 { get; set; }
        public virtual VIGENCIAS VIGENCIAS { get; set; }
    }
    
}
