//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_INFOCONT
    {
        public INT_INFOCONT()
        {
            this.INT_INCO_SOP = new HashSet<INT_INCO_SOP>();
        }
    
        public string COD_CON { get; set; }
        public Nullable<System.DateTime> FEC_INF { get; set; }
        public Nullable<System.DateTime> FEC_INI { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
        public Nullable<decimal> CAN_HOJ { get; set; }
        public decimal NUM_INF { get; set; }
        public Nullable<System.DateTime> FE_REG { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public string EST_INF { get; set; }
        public string DES_INF { get; set; }
    
        public virtual ICollection<INT_INCO_SOP> INT_INCO_SOP { get; set; }
    }
    
}
