//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INTANT_CONT
    {
        public Nullable<int> ID_CONT { get; set; }
        public string COD_INVAN { get; set; }
        public decimal VAL_INVAN { get; set; }
        public decimal VPORCENT { get; set; }
        public string EST_INVAN_CONT { get; set; }
    
        public virtual INTINVAN INTINVAN { get; set; }
    }
    
}
