//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INTDOCACTAS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> IDE_ACTA { get; set; }
        public byte[] DOC_DOC { get; set; }
        public byte[] DOC_PDF { get; set; }
        public byte[] DOC_BAS { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public string USAPMOD { get; set; }
        public string USBDMOD { get; set; }
        public string ESTADO { get; set; }
    }
    
}
