//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INTENTSEGSOCIAL
    {
        public string COD_ENT { get; set; }
        public string NOM_ENT { get; set; }
        public string TIPO_ENT { get; set; }
        public string EST_ENT { get; set; }
    
        public virtual INTTIPO_ESS INTTIPO_ESS { get; set; }
    }
    
}
