//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INTTIPO_ESS
    {
        public INTTIPO_ESS()
        {
            this.INTENTSEGSOCIAL = new HashSet<INTENTSEGSOCIAL>();
        }
    
        public string COD_TIP { get; set; }
        public string NOM_TIP { get; set; }
        public string EST_TIP { get; set; }
    
        public virtual ICollection<INTENTSEGSOCIAL> INTENTSEGSOCIAL { get; set; }
    }
    
}
