//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class MENU
    {
        public string MENUID { get; set; }
        public string DESCRIPCION { get; set; }
        public string PADREID { get; set; }
        public int POSICION { get; set; }
        public string ICONO { get; set; }
        public short HABILITADO { get; set; }
        public string URL { get; set; }
        public string PERFIL { get; set; }
    }
    
}
