//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class MENU2
    {
        public MENU2()
        {
            this.MENU_PERFIL = new HashSet<MENU_PERFIL>();
            this.MENU211 = new HashSet<MENU2>();
        }
    
        public string MENUID { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string PADREID { get; set; }
        public int POSICION { get; set; }
        public string ICONO { get; set; }
        public short HABILITADO { get; set; }
        public string URL { get; set; }
        public string MODULO { get; set; }
        public string ROLES { get; set; }
        public string TARGET { get; set; }
        public string PPAL { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FREG { get; set; }
        public Nullable<System.DateTime> FNOV { get; set; }
    
        public virtual ICollection<MENU_PERFIL> MENU_PERFIL { get; set; }
        public virtual MENU2 MENU21 { get; set; }
        public virtual MENU2 MENU22 { get; set; }
        public virtual ICollection<MENU2> MENU211 { get; set; }
        public virtual MENU2 MENU23 { get; set; }
    }
    
}
