//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class MODULOS
    {
        public string COD_MOD { get; set; }
        public string NOM_MOD { get; set; }
        public Nullable<decimal> ORD_MOD { get; set; }
        public string EST_MOD { get; set; }
        public string DES_MOD { get; set; }
    }
    
}
