//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class NROCONVIG
    {
        public short YEAR_VIG { get; set; }
        public string COD_TIP { get; set; }
        public Nullable<int> NRO_INI_CON { get; set; }
        public Nullable<int> NRO_ACT_CON { get; set; }
        public Nullable<decimal> POR_ADI_VIG { get; set; }
    
        public virtual TIPOSCONT TIPOSCONT { get; set; }
    }
    
}
