//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class NUMPROP
    {
        public string TIP_PROP { get; set; }
        public Nullable<decimal> NUM_INI { get; set; }
        public Nullable<decimal> NUM_ACT { get; set; }
    }
    
}
