//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PCRONO_DIAS
    {
        public decimal ID_CRONO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
    
        public virtual PCRONOGRAMAS PCRONOGRAMAS { get; set; }
    }
    
}
