//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PCRONOGRAMAS
    {
        public PCRONOGRAMAS()
        {
            this.PCRONO_DIAS = new HashSet<PCRONO_DIAS>();
        }
    
        public string COD_ACT { get; set; }
        public string NOM_ACT { get; set; }
        public string COD_TPRO { get; set; }
        public Nullable<System.DateTime> FECHAI { get; set; }
        public Nullable<decimal> HORAI { get; set; }
        public Nullable<System.DateTime> FECHAF { get; set; }
        public Nullable<decimal> HORAF { get; set; }
        public string UBICACION { get; set; }
        public string NOTAS { get; set; }
        public string OCUPADO { get; set; }
        public string EST_ACT { get; set; }
        public string OBS_SEG { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP_MOD { get; set; }
        public string USBD_MOD { get; set; }
        public string NUM_PROC { get; set; }
        public decimal ID { get; set; }
        public string COLOR { get; set; }
        public string ANULADO { get; set; }
        public string OBLIGATORIO { get; set; }
        public string EST_PROC { get; set; }
        public Nullable<decimal> DIAS_AVISO { get; set; }
        public System.DateTime FEC_AVISO { get; set; }
        public string MIN_I { get; set; }
        public string MIN_F { get; set; }
        public string NOTIFICAR { get; set; }
        public string MFECINI { get; set; }
        public string MHORINI { get; set; }
        public string MFECFIN { get; set; }
        public string MHORFIN { get; set; }
        public Nullable<int> ORDEN { get; set; }
    
        public virtual PCONTRATOS PCONTRATOS { get; set; }
        public virtual ICollection<PCRONO_DIAS> PCRONO_DIAS { get; set; }
        public virtual PESTADOSACT PESTADOSACT { get; set; }
    }
    
}
