//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PESTADOSACT
    {
        public PESTADOSACT()
        {
            this.PCRONOGRAMAS = new HashSet<PCRONOGRAMAS>();
        }
    
        public string COD_EST { get; set; }
        public string NOM_EST { get; set; }
        public string IMAGEN { get; set; }
        public string COLOR { get; set; }
        public string IS_FINAL { get; set; }
    
        public virtual ICollection<PCRONOGRAMAS> PCRONOGRAMAS { get; set; }
    }
    
}
