//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PESTADOS
    {
        public PESTADOS()
        {
            this.GPROCESOS = new HashSet<GPROCESOS>();
            this.PACTIVIDADES = new HashSet<PACTIVIDADES>();
            this.PCONTRATOS = new HashSet<PCONTRATOS>();
        }
    
        public string COD_EST { get; set; }
        public string NOM_EST { get; set; }
        public string IMAGEN { get; set; }
        public string COLOR { get; set; }
        public string FINAL { get; set; }
        public Nullable<decimal> ORDEN { get; set; }
    
        public virtual ICollection<GPROCESOS> GPROCESOS { get; set; }
        public virtual ICollection<PACTIVIDADES> PACTIVIDADES { get; set; }
        public virtual ICollection<PCONTRATOS> PCONTRATOS { get; set; }
    }
    
}
