//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PGCONTRATOSM
    {
        public string NUM_PROC { get; set; }
        public byte[] MINUTA { get; set; }
        public decimal ID { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
        public int GRUPO { get; set; }
        public string USAP { get; set; }
        public byte[] MINUTABASE { get; set; }
        public string EDITABLE { get; set; }
        public byte[] MINUTAPDF { get; set; }
    }
    
}
