//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PLANTILLAPPAL
    {
        public string NOMBRE { get; set; }
        public byte[] PLANTILLA { get; set; }
        public decimal ID { get; set; }
    }
    
}
