//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class POLIZAS_ADICIONES
    {
        public string NRO_ADI { get; set; }
        public int COD_POL { get; set; }
        public int COD_ASE { get; set; }
        public int VAL_POL { get; set; }
        public System.DateTime FEC_POL { get; set; }
        public decimal NRO_POL { get; set; }
    
        public virtual ASEGURADORAS ASEGURADORAS { get; set; }
        public virtual POLIZAS POLIZAS { get; set; }
    }
    
}
