//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PPLANTILLAS
    {
        public PPLANTILLAS()
        {
            this.PPLANTILLAS_FORMATO_TABLAS = new HashSet<PPLANTILLAS_FORMATO_TABLAS>();
        }
    
        public decimal IDE_PLA { get; set; }
        public string TIP_PLA { get; set; }
        public string NOM_PLA { get; set; }
        public byte[] PLANTILLA { get; set; }
        public string EXT { get; set; }
        public string EST_PLA { get; set; }
        public string COD_STIP { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD_MOD { get; set; }
        public string USAP_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string CLAVE { get; set; }
        public string EDITABLE { get; set; }
    
        public virtual ICollection<PPLANTILLAS_FORMATO_TABLAS> PPLANTILLAS_FORMATO_TABLAS { get; set; }
    }
    
}
