//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PPLANTILLAS_CAMPOS
    {
        public string NOM_CAM { get; set; }
        public string NOM_PLA { get; set; }
        public string DES_CAM { get; set; }
        public string TIP_DAT { get; set; }
        public string EST_CAM { get; set; }
        public string GTABLA { get; set; }
        public string NTABLA { get; set; }
        public string ENCABEZADO_PIE { get; set; }
        public string MOSTRAR_TITULOS { get; set; }
        public string MOSTRAR_BORDE { get; set; }
        public string VISTA { get; set; }
        public string MARCADOR { get; set; }
        public Nullable<decimal> IDE_PLA { get; set; }
        public Nullable<decimal> COL_FINAL { get; set; }
        public string TAGRUPADA { get; set; }
        public string COLS_GRUPO { get; set; }
    }
    
}
