//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PPLANTILLAS_FORMATO_TABLAS
    {
        public decimal IDE_PLA { get; set; }
        public string NTABLA { get; set; }
        public string NOM_CAM { get; set; }
        public string DES_CAM { get; set; }
        public string TIP_DAT { get; set; }
        public Nullable<decimal> ANCHO { get; set; }
    
        public virtual PPLANTILLAS PPLANTILLAS { get; set; }
    }
    
}
