//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PPOLIZAS
    {
        public decimal COD_POL { get; set; }
        public string NUM_PROC { get; set; }
        public Nullable<decimal> POR_SMMLV { get; set; }
        public string CAL_APARTIRDE { get; set; }
        public Nullable<decimal> VIGENCIA { get; set; }
        public string APARTIRDE { get; set; }
        public string CUBRIMIENTO { get; set; }
    
        public virtual CAL_VIG_POL CAL_VIG_POL { get; set; }
        public virtual CALCULOPOL CALCULOPOL { get; set; }
        public virtual PCONTRATOS PCONTRATOS { get; set; }
    }
    
}
