//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PSOLICITUDES
    {
        public PSOLICITUDES()
        {
            this.HREVISADO = new HashSet<HREVISADO>();
        }
    
        public decimal NUM_SOL { get; set; }
        public string COD_SOL { get; set; }
        public string DEP_SOL { get; set; }
        public string DEP_PSOL { get; set; }
        public short VIG_SOL { get; set; }
        public string TIP_CON { get; set; }
        public string STIP_CON { get; set; }
        public string COD_TPRO { get; set; }
        public string OBJ_SOL { get; set; }
        public string ID_ABOG_ENC { get; set; }
        public Nullable<System.DateTime> FECHA_ASIGNADO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public Nullable<decimal> NUM_PLA { get; set; }
        public Nullable<System.DateTime> FEC_RECIBIDO { get; set; }
        public Nullable<decimal> VAL_CON { get; set; }
        public string USAP_MOD { get; set; }
        public Nullable<decimal> ID_HREV { get; set; }
        public string COD_EP { get; set; }
    
        public virtual DEPENDENCIA DEPENDENCIA { get; set; }
        public virtual DEPENDENCIA DEPENDENCIA1 { get; set; }
        public virtual TERCEROS TERCEROS { get; set; }
        public virtual TIPOSPROC TIPOSPROC { get; set; }
        public virtual SUBTIPOS SUBTIPOS { get; set; }
        public virtual TIPOSCONT TIPOSCONT { get; set; }
        public virtual ICollection<HREVISADO> HREVISADO { get; set; }
        public virtual HREVISADO HREVISADO1 { get; set; }
    }
    
}
