//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class RP_CONTRATOS
    {
        public string NRO_RP { get; set; }
        public string COD_CON { get; set; }
        public System.DateTime FEC_RP { get; set; }
        public short VIGENCIA { get; set; }
        public string DOC_SOP { get; set; }
        public Nullable<decimal> VAL_RP { get; set; }
        public Nullable<decimal> VAL_PAGO { get; set; }
        public string USAP { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
    }
    
}
