//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class RUBROS_RCONTRATOS
    {
        public string COD_CON { get; set; }
        public string COD_RUB { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string NRO_CDP { get; set; }
        public string VIGENCIA_CDP { get; set; }
    }
    
}
