//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class RUBROS_ADICIONES
    {
        public string COD_RUB { get; set; }
        public string NRO_ADI { get; set; }
        public string NOM_RUB { get; set; }
        public Nullable<decimal> VAL_COMPROMISO { get; set; }
    }
    
}
