//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class SUBTIPOS
    {
        public SUBTIPOS()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.MOD_CONTRATOS = new HashSet<MOD_CONTRATOS>();
            this.ESTPREV = new HashSet<ESTPREV>();
            this.PSOLICITUDES = new HashSet<PSOLICITUDES>();
        }
    
        public string COD_STIP { get; set; }
        public string NOM_STIP { get; set; }
        public string COD_TIP { get; set; }
        public string CLA_CON_DEP { get; set; }
        public string CRT_F20_1A { get; set; }
        public string CLA_CON_DP { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<MOD_CONTRATOS> MOD_CONTRATOS { get; set; }
        public virtual TIPOSCONT TIPOSCONT { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES { get; set; }
    }
    
}
