//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class SUPERVISORES_CONTRATO
    {
        public string IDE_SUP { get; set; }
        public string COD_CON { get; set; }
    
        public virtual TERCEROS TERCEROS { get; set; }
    }
    
}
