//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TERCEROS
    {
        public TERCEROS()
        {
            this.CONSORCIOSUT = new HashSet<CONSORCIOSUT>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.HDEP_ABOGADOS = new HashSet<HDEP_ABOGADOS>();
            this.INT_GP_USU_ROL = new HashSet<INT_GP_USU_ROL>();
            this.INTERVENTORES_CONTRATO = new HashSet<INTERVENTORES_CONTRATO>();
            this.SUPERVISORES_CONTRATO = new HashSet<SUPERVISORES_CONTRATO>();
            this.ESTPREV = new HashSet<ESTPREV>();
            this.ESTPREV1 = new HashSet<ESTPREV>();
            this.ESTPREV2 = new HashSet<ESTPREV>();
            this.ESTPREV3 = new HashSet<ESTPREV>();
            this.ESTPREV4 = new HashSet<ESTPREV>();
            this.ESTPREV5 = new HashSet<ESTPREV>();
            this.ESTPREV6 = new HashSet<ESTPREV>();
            this.PCONTRATOS = new HashSet<PCONTRATOS>();
            this.EP_HESTADOEP = new HashSet<EP_HESTADOEP>();
            this.PSOLICITUDES = new HashSet<PSOLICITUDES>();
            this.HREVISADO = new HashSet<HREVISADO>();
        }
    
        public string IDE_TER { get; set; }
        public string APE1_TER { get; set; }
        public string DIR_TER { get; set; }
        public string TEL_TER { get; set; }
        public string EMA_TER { get; set; }
        public string APE2_TER { get; set; }
        public string NOM1_TER { get; set; }
        public string NOM2_TER { get; set; }
        public string TIP_IDE { get; set; }
        public string EXP_IDE { get; set; }
        public string DV_TER { get; set; }
        public string RAZ_SOC { get; set; }
        public string ORD_GAS { get; set; }
        public string CAR_FUN { get; set; }
        public string DOC_DEL { get; set; }
        public Nullable<System.DateTime> FEC_DEL { get; set; }
        public string DEP_NEC { get; set; }
        public string ESTADO { get; set; }
        public string TIPO { get; set; }
    
        public virtual ICollection<CONSORCIOSUT> CONSORCIOSUT { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<HDEP_ABOGADOS> HDEP_ABOGADOS { get; set; }
        public virtual ICollection<INT_GP_USU_ROL> INT_GP_USU_ROL { get; set; }
        public virtual ICollection<INTERVENTORES_CONTRATO> INTERVENTORES_CONTRATO { get; set; }
        public virtual ICollection<SUPERVISORES_CONTRATO> SUPERVISORES_CONTRATO { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV1 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV2 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV3 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV4 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV5 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV6 { get; set; }
        public virtual ICollection<PCONTRATOS> PCONTRATOS { get; set; }
        public virtual ICollection<EP_HESTADOEP> EP_HESTADOEP { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES { get; set; }
        public virtual ICollection<HREVISADO> HREVISADO { get; set; }
    }
    
}
