//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TIP_DOC
    {
        public TIP_DOC()
        {
            this.ANX_CONTRATOS = new HashSet<ANX_CONTRATOS>();
        }
    
        public string COD_TIP { get; set; }
        public string DES_TIP { get; set; }
        public string EST_TIP { get; set; }
        public string COD_ETAPA { get; set; }
        public string ORIGEN { get; set; }
    
        public virtual ICollection<ANX_CONTRATOS> ANX_CONTRATOS { get; set; }
    }
    
}
