//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TIPOSCONT
    {
        public TIPOSCONT()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.MOD_CONTRATOS = new HashSet<MOD_CONTRATOS>();
            this.NROCONVIG = new HashSet<NROCONVIG>();
            this.SUBTIPOS = new HashSet<SUBTIPOS>();
            this.PSOLICITUDES = new HashSet<PSOLICITUDES>();
        }
    
        public string COD_TIP { get; set; }
        public string NOM_TIP { get; set; }
        public string EST_TIP { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<MOD_CONTRATOS> MOD_CONTRATOS { get; set; }
        public virtual ICollection<NROCONVIG> NROCONVIG { get; set; }
        public virtual ICollection<SUBTIPOS> SUBTIPOS { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES { get; set; }
    }
    
}
