//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TIPO_PLAZOS
    {
        public TIPO_PLAZOS()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.MOD_CONTRATOS = new HashSet<MOD_CONTRATOS>();
            this.ESTPREV = new HashSet<ESTPREV>();
            this.ESTPREV1 = new HashSet<ESTPREV>();
        }
    
        public string COD_TPLA { get; set; }
        public string NOM_PLA { get; set; }
        public Nullable<decimal> ORD_TPLA { get; set; }
        public string EST_TPLA { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<MOD_CONTRATOS> MOD_CONTRATOS { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV1 { get; set; }
    }
    
}
