//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TIPO_AGENT
    {
        public string TAG_COD { get; set; }
        public string TAG_NOM { get; set; }
        public string TAG_EST { get; set; }
        public string TAG_USAP { get; set; }
        public string TAG_USBD { get; set; }
        public Nullable<System.DateTime> TAG_FREG { get; set; }
        public Nullable<System.DateTime> TAG_FNOV { get; set; }
        public Nullable<decimal> TAG_ORD { get; set; }
    }
    
}
