//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TIPO_PAGO
    {
        public TIPO_PAGO()
        {
            this.CFORMA_PAGO = new HashSet<CFORMA_PAGO>();
            this.MOD_CFORMA_PAGO = new HashSet<MOD_CFORMA_PAGO>();
            this.PAGOS_GPROCESOS = new HashSet<PAGOS_GPROCESOS>();
            this.PAGOS_PARCIALES = new HashSet<PAGOS_PARCIALES>();
            this.EP_FORMA_PAGO = new HashSet<EP_FORMA_PAGO>();
        }
    
        public string ID_PAGO { get; set; }
        public string DES_PAGO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USBD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<CFORMA_PAGO> CFORMA_PAGO { get; set; }
        public virtual ICollection<MOD_CFORMA_PAGO> MOD_CFORMA_PAGO { get; set; }
        public virtual ICollection<PAGOS_GPROCESOS> PAGOS_GPROCESOS { get; set; }
        public virtual ICollection<PAGOS_PARCIALES> PAGOS_PARCIALES { get; set; }
        public virtual ICollection<EP_FORMA_PAGO> EP_FORMA_PAGO { get; set; }
    }
    
}
