//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TIPPROPONENTE
    {
        public TIPPROPONENTE()
        {
            this.GPPROPONENTES = new HashSet<GPPROPONENTES>();
            this.MOD_PROPONENTES = new HashSet<MOD_PROPONENTES>();
            this.PPROPONENTES = new HashSet<PPROPONENTES>();
        }
    
        public string COD_TIPPROP { get; set; }
        public string NOM_TIPPROP { get; set; }
    
        public virtual ICollection<GPPROPONENTES> GPPROPONENTES { get; set; }
        public virtual ICollection<MOD_PROPONENTES> MOD_PROPONENTES { get; set; }
        public virtual ICollection<PPROPONENTES> PPROPONENTES { get; set; }
    }
    
}
